CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(80) NOT NULL,
 username_small VARCHAR(80) NOT NULL UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 avatar VARCHAR(255) NOT NULL DEFAULT '',
 role VARCHAR(16) NOT NULL DEFAULT 'user',
 active TINYINT NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 csrf CHAR(64) NOT NULL,
 expires_at DATETIME NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS password_resets (
 token_hash CHAR(64) PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 expires_at DATETIME NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS titles (
 id CHAR(64) PRIMARY KEY,
 media_type VARCHAR(16) NOT NULL,
 external_id VARCHAR(40) DEFAULT NULL,
 title VARCHAR(255) NOT NULL,
 original_title VARCHAR(255) NOT NULL DEFAULT '',
 normalized_title VARCHAR(255) NOT NULL,
 year SMALLINT DEFAULT NULL,
 poster TEXT NOT NULL,
 backdrop TEXT NOT NULL,
 overview TEXT NOT NULL,
 rating DECIMAL(4,2) DEFAULT NULL,
 genres TEXT NOT NULL,
 language VARCHAR(16) NOT NULL DEFAULT '',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX (normalized_title), INDEX (media_type, year),
 UNIQUE KEY external_identity (media_type, external_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sources (
 id CHAR(64) PRIMARY KEY,
 title_id CHAR(64) NOT NULL,
 provider_id INT NOT NULL,
 href TEXT NOT NULL,
 label VARCHAR(255) NOT NULL,
 FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE CASCADE,
 INDEX (title_id, provider_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS favourites (
 user_id BIGINT UNSIGNED NOT NULL,
 title_id CHAR(64) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (user_id, title_id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS progress (
 user_id BIGINT UNSIGNED NOT NULL,
 item_id CHAR(64) NOT NULL,
 title_id CHAR(64) NOT NULL,
 source_id CHAR(64) NOT NULL,
 href TEXT NOT NULL,
 label VARCHAR(255) NOT NULL,
 season_number INT DEFAULT NULL,
 episode_number INT DEFAULT NULL,
 position_seconds INT NOT NULL DEFAULT 0,
 duration_seconds INT NOT NULL DEFAULT 0,
 completed TINYINT NOT NULL DEFAULT 0,
 tracking VARCHAR(16) NOT NULL DEFAULT 'opened',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (user_id, item_id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE CASCADE,
 INDEX (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cache (
 cache_key CHAR(64) PRIMARY KEY,
 payload LONGTEXT NOT NULL,
 expires_at DATETIME NOT NULL,
 stale_until DATETIME NOT NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS refresh_jobs (
 cache_key CHAR(64) PRIMARY KEY,
 provider_id INT NOT NULL,
 operation VARCHAR(16) NOT NULL,
 args TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS provider_health (
 provider_id INT PRIMARY KEY,
 state VARCHAR(20) NOT NULL,
 error_code VARCHAR(80) DEFAULT NULL,
 latency_ms INT NOT NULL DEFAULT 0,
 last_success DATETIME DEFAULT NULL,
 checked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY,
 hits INT NOT NULL DEFAULT 1,
 window_start INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
